---
title: Crisis Management using Sentimental Analysis from Twitter:Addressing Response Rate of Crisis Management Departments using NLP
author:
  - name: Getrude Gichuhi
    email: getrude.gichuhi@strathmore.edu
    affiliation: Strathmore University

abstract: |
  One of the most widely used social media platform is twitter, which creates augmented decision support systems through big data analytics. As one of the sources used to mine data, twitter users, interact to discuss current affairs, and several topics which are distributed in real time, specifying the location, and time of the individual. This study measures the response level to crisis and the management of time through identifying a crisis and areas most likely for crisis occur. Twitter has become one of the networks used for emergency communications and check on situations affecting people in different areas. Although, availability of social media data is huge, open and mostly free, there is a limitation on how analysts and/or researchers are making sense of the data, implicating to the fact of lack of data literacy of the company or the individuals. The data involved, could have high volume, be different, have huge velocity, value, variability, and veracity.  As much as governments and rescue teams from different NGOs have their own crisis management policies, sentiments of data mined from twitter, determines the success of the crisis response and recovery process. The model used in the paper, classifies the needs of the affected people during the crisis using ML algorithm and NLP for analysing the sentiment of the people on response time from Twitter time series data.This research, will operate as a basis of providing useful intel, and actionable information to crisis management and mitigation teams for planning, preparation and response to disasters and possibly adapt by adopting the algorithms used here into an automated system that helps them respond immediately to crises

Keywords: Twitter, Sentiment Analysis, Text classification, crises response, Machine Learning, Natural Language Processing.

bibliography: reference.bib
csl: acm-sig-proceedings.csl
output: rticles::acm_article
---

# Introduction 
Twitter currently serves close to 400 million users and is seen to be one of the top 3 social media networking apps. With user bracket between 26-35 years, it is the best and fastest place to acquire current information of what is happening around the world or a national level. For instance, in cases of traffic, if one would like to find the cause of traffic, whether an accident occurred or there was a car that got stuck and all, the right place to acquire such info is from twitter.  The Haiti earthquake incident led to usage of technology for crisis response, since there was an analyzation of people’s emotions through twitter in relation to the disaster caused @gurman_ellenberger_2015. The Ushahidi tool was also used to capture the events that occurred during the post-election violence in Kenya and how to recover after all the crisis in certain parts of Kenya.
With its popularity on the different use cases, Twitter is becoming on of the most used social media platforms for data science problems, especially when it comes to using it as data source for text analytics, sentiment and opinion mining, topic modeling, text classification and summarization. Besides traffic, and earthquakes or fire incidents, twitter has also been used on diseases tracking, modeling in pandemics and epidemics, estimating financial fluctuations on stock of goods and services, generating insights on different personalities of customers, employee satisfaction, polls on elections situations and so on. The use of crisis response and management began around 2007, when wildfires in California was discussed a lot. Twitter as a source of extracting data is a challenging task, since it drills down to quality of data, reliability and validation especially on it facilitating the preparation and planning of response and management to crises. 
The focus is to set out analysis of content from twitter feeds collected during crisis, with an aim to generate insights, specifically sentiments divergence, subjectivity and verbality, as well as classify tweets into different categories for response teams. The first aim, analysis the emotions, reactions to incidents, and sympathy based on the incidents of different people from their tweets, the study also looks on how fast NGOs are responding to crisis to salvage situations happening around them.


# Background
In early stages of NGO’s responding to crisis, before social media and mobile networks such as short message service (SMS) @qadir_ali_ur, messagers were sent to reach help centers to request for assistance when incidents had occurred. With the introduction of the internet era, it became a perfect opportunity to mine valuable insights from the mostly used sources of various situations and analyze the data. One of the main sources of social media, is Twitter, which with current trending situations, fast and available information trickles in from tweeps who are either directly affected or offers information of what exactly is happening at the grounds.  Recently, Twitter introduced Twitter Spaces, which involves live audio conversations of current affairs affecting lives of people living in a certain country. With the use of NLP, the audio conversations can be analyzed to pick the mostly used words when it comes to conversations.  Social media platforms have been considered as the safest place to share one’s reviews and critiques about anything that affects the lives of humans, for instances, politics, products, or services or even entertainment news or sports news such as marathon races.  
An increase of social media with updated versions that provide information during crisis. This has enable different organizations, governments and private sectors to respond quickly and effectively to public sentiments during disasters on specified areas. With sentiment analysis especially from Twitter, is used to identify patterns and trends through hashtags, which at times are similar to other countries. For instance, Police brutality that happened in Kenya, was initiated by a casing point of how different people reacted to George Floyd’s case who was wrongly accused by the police, and there after getting killed due to him held down by one of the police, other instances of similar mishandling of different people in Kenya became common, and everyone on twitter complained to ensure that such patterns could be stopped. Sentimental analysis, can be used in decision-making and develop strategies such as policies and government measures to be implemented. 
According to Chadha @sipper_2020, the phases of crisis management include mitigation, preparedness, response, and recovery. As for response and recovery, they require user generated content from Twitter, and other social media platforms and imaginary sites using drones or satellites. With such access to information, situations are likely to be handled effectively. Crises are mostly disturbing, and at times lead to death or too much bleeding, or even loss of belongings, however, they bring people together by creating sympathy and a philanthropic community with people rushing to help each other out of situations that seem harmful. 
Application of data analytics is patched to several areas, such as health analytics, financial analytics, construction areas, climate science with predictions, telecommunications, trading analytics and so much more.
However, the application of data analytics to analyze crisis or situational response, is still at its early stages.  In event of a crisis, and acquiring the right information, it is then necessary for disaster response teams or companies to react by helping the affected individuals.  For a team to respond, they would mostly rely on alarms from community members if there were any, community gatekeepers or even incomplete data shared on social media. But when huge data is mined from social media, use of computational statistics, Natural Language Processing and big data analytics assists in modeling the perfect algorithm for a response to be undertaken. 


# Statement of the Problem
Crisis do occur time to time at various areas, and social media has enabled sharing of videos, photos, and audio to be easily accessible, which makes response of certain situations to occur faster. Although, there is inefficiency on quick response, and accurately understand what the public needs are, crisis management departments from NGOs, governments, public and private sectors are faced with large volume of data from twitter, the velocity of the data shared, and at times it could be insufficient and gauging it’s relevance.  In Narok, one of the major response to crisis from crisis management departments was the use of warning alarms used to help people be aware of certain situations, such as, landslides or flash floods or earthquakes, which enabled people, to rush to high lands or safe area regions. 
With the help of Twitter, where tweets are mined immediately to acquire knowledge of where an incident is happening assists in understanding how to respond to the situations.  This study explored on ways that sentimental analysis could be used to respond and recover to crises during and after the incidents

# Objectives
The main objective of the study is to use sentiments from Twitter to analyze people’s sentiment during crisis and help rescue teams to identify patterns and trends that can aid in responding quickly to crisis

## Specific Objectives 
1. To identify social media influencers who affect how responses of crisis shapes opinion and how to deal with situations at hand. 
2. To map out geographical areas that are likely to be affected by crisis and tailor crisis management strategies for mitigation purposes. 
3. To integrate social media data frameworks into crisis management systems and processes for keen alertness. 

## Research Questions 
1. What are the characteristics and behaviors of social media influencers during crisis, and how do they affect response from the public as well as from crisis management departments?
2. What are the geographical patterns of sentiments during crisis and how can they be used to tailor strategies on response for certain areas?
3. How can social media data be integrated into crisis management systems and processes as a common framework that can be used to improve responses to crisis?

# Importance of the Study
The study will be of importance to the government, different organizations and NGOs with rescue teams, in responding to crises, improve their response rates, tailor-make strategies that align with specific concerns and also putting into consideration the culture and language of certain areas.  It will also be of importance to other scholars who gather information on algorithms used in response to crises or those involved in psychology to study how human beings behave when there are incidents and people are affected.

# Scope of the study 
The study focuses on various aspects that aids in the implementation of the study, which include but not limited to:
a)	Data: Data will be collected from Twitter and NLP techniques will be used. 
b)	Sentimental Analysis: ML models will be used to train the sentiments from tweet posts during crisis situations.
c)	Integration of Social media data: Development of a framework to be used in crisis management systems 
d)	Geographical mapping: With the use of maps, it will map out areas likely to be affected by social media crisis based on past incidents
Besides these, the study will also evaluate how crisis management departments are responding to crisis, based on sentiments from tweets and how influencers come in to aid the response. 
# Summary 
This chapter introduces the use of sentiment analysis from twitter in crisis situations from different geographical areas and from different management departments. It discusses the main problem that crisis management rescue teams face is the velocity of the data and the increased volume of the data and how quickly they respond to the public needs during crisis. The objectives of the study were to identify key social media influences, map out geographical areas likely to have crisis occur, and integrating social media in organizations frameworks.
The research questions addressed based on the objectives of the study. The scope and the importance of the study, was to aid, understand where the data will be collected from, what type of data will be collected, the demographics of the areas to be mapped out, and to whom these data is useful to and how they can integrate into their systems.
The next chapter, dives deep into understanding the main objectives, as discussed in chapter one, the research done by previous scholars and the gaps that are still yet to be studied. 


# Literature Review
This chapter begins with identifying relevant studies conducted based in advanced areas, the study involved use of NLP, and how social media data has been used during crisis. It also dives into studies done on the response of different rescue teams, integration of social media data in systems and processes as well as geographical areas that are prone to crisis. Afterwards the study will identify gaps and what further research would be needed. 

# Related Studies
There are a number of studies that have been carried out in the last few years, that research on the use of sentimental analysis from social media in handling crisis management. For instance, in 2012, Naoko did a study of the Japan Tsunami, that occurred in 2011, where she analyzed 2.5 million tweets that were posted with the first three days of the Tsunami. Her findings relayed how tweets provided real-time updates of the disaster, personal experiences and observations and also most importantly how rescue and recovery teams organized and coordinated themselves. However, some of the limitations that were observations in the study was the aspect of language barrier, especially since some were in Japanese. 
Another example of a sentiment analysis for crisis management was done by Sriram in 2013, that was to help in monitoring and understanding public sentiment during a Uttarakhand floods crisis in india. One of the key things that the study highlighted was the two-step approach of pre-processing and classification which included, the EDA process, and training and testing the tweets into three categories of Negative, Positive and Neutral. Among the challenges, highlighted from the paper, include the identifying the use of sarcasm, irony and emotions, from the tweets that affected the accuracy of the analysis. The Uttarakhand floods in India, was also researched by other scholars where they proposed a system for a real-time sentiment analysis, for purposes of aiding crisis management efforts. Under this study, they collected data using Twitter streaming API to collect tweets in real time, there after undertaking it through the Pre-processing step, and finally modeling of the data. Since it was a time series project, it’s importance was highlighted when they found out that responding teams could understand sentiments and offer help immediately by dispatching teams to the mapped-out areas. 
In 2015, a study was carried out to identify early warning signs of crises through monitoring social media data. The study was based on the Ebola outbreak which was categorized as an epidemic disease which occurred in 2014 in West Africa. It identified early warning signs of the outbreak through monitoring the sentiments from social media posts. The positive effect to the study was to aid the concerned departments to actually respond to potential cases when it comes to Ebola outbreak. 

# Data Analytics and Natural Language Processing  
In the 4th industrial era, technology has been advancing over and over, and new ways of acquiring information has become proficient from different sources. However, besides that a lot of data exchanged is growing very fast, these high volumes of data exchanged are referred to as Big Data. It is when large amount of data is used to find insights and unhidden meaning @sas_2022.  When mining data, it comes in two types, which include the structured data and unstructured data. Big data analytics best deals with unstructured data, since previous tools cannot handle unstructured data. 
Data from twitter can be used in response to crisis by communicating with people through the crisis and after the crisis response, also through detecting warning alarms used in case of an incident about to happen as well as offer information to rescue teams to respond immediately. There are several areas where data analytics has been applied to ensure that it shows a response to crisis affecting different areas. For instance, population surveillance and urban analytics, where data is used to track the movement of crisis affected areas, in Kenya this would have been effective especially during the post-election violence to map out areas where fights are happening. Also in reality data mining, which involves extraction and patterns studied of how groups of individuals are behaving. Outliers detection especially if there are any anomalies of a certain area. 

# Technologies of Big Data sharing 
The sources used to share some of the data especially in times of crisis, are the ones that assist fast response to crisis from the rescue teams nearby.  These technologies have become more elastic in this era, to the point that most countries have considered them as the future of human progress to response of their wellbeing. 
Smartphones are fast becoming the center of communication devices with almost everyone around the world. Besides communication, mobile phones are used to track location of people, activities such as walking, and speech recognition among other things @lane_miluzzo_lu_peebles_ choudhury_campbell_2020. This makes response to crisis even easier to detect especially if mobile phones can be used as sensors and rescue teams can acquire information directly from individuals, especially through SMS based technologies such as WhatsApp, signal, and telegram. 
Nowadays, the internet connection is enabling most countries and its societies to grow and course a paradigm shift of how different communications should be implemented. Especially to the use of open-source data, some of the ways of how rescue teams respond to disasters have been initiated especially in African countries such as Kenya. Open-source data can be found in social media platforms such as twitter, Facebook, and Instagram. For instance, the flash floods that occurred in Naivasha Gorge in 2019, twitter had access to the data and was accessible to several people. Three ways of mitigations are deduced from accessing data from twitter, structural mining of data, the philanthropic acts of the people and the empowerment of community members in improvement of warning systems and resources to ensure passage of water. 
There are several applications used especially when it comes to use of social media to acquire information of certain situations. They include, predicting election results, movie performance on Netflix, natural disasters such as flash floods, financial markets for instance cryptocurrencies. The only main difference comes in on the spatial representation of these applications, for instance when visuals of election votes as per city can be compare with a univariate model, however, when looking into financial markets can vary per individuals in a city. 
 
# Sentiment Analysis
Sentiment Analysis is the contextual mining of text which identifies and extracts subjective information in source material and helps determine the emotional tone they carry, whether they are positive, negative, or neutral @gupta_2018. The first work on using sentiment analysis was done by Pang, Lee and Vaithyanathan @pang_lee_vaithyanathan_2002, where they classified movie reviews into positive and negatives rating using machine learning classification. Other authors started developing machine learning algorithms to implement the use of sentiment analysis. Around 2011 @aramaki_maskawa_morita_2011, a study on influenza disease outbreak was carried out using support vector Machine (SVM), however, use of Natural Language processing (NLP)techniques was better since they improved the classification with an accuracy of 95% confidence. 
Sentiment analysis depends on detecting the insights of the hidden subjective expressions in the text mined from twitter. There are several features that different researchers used such as Adjective verb Adverb (AVA), used to classify the subject in a sentence. Meaning the adjectives and the adverbs are used to calculate how much sentiment involvement is in that sentence. Another feature is the use of the lexicon, which refers to the type of vocabulary used or language depending on where one comes from. 
Today sentiment analysis are used as warning systems to reduce crisis damage or respond to crisis of a certain event. According to Sen, Rudra and Ghosh @sen_rudra_ ghosh_2015, studied the sentiment analysis and classified them into various categories such as personal, or impersonal subjectivity formal language and informal language text. As much as a number of studies have been done to measure the emotions and view of people during crises, still there is no match up identification of the sentiment of the people towards the aid they receive when in crises. Effective classification of the data will help the rescue teams in building trust, courage, and confidence among the people during the events of the crisis

# Crisis and Emergency Mapping
Crisis occur in different forms, such as natural disasters for instance, landslides, flash floods, or and drought, other forms include human-caused incidents, which include, oil spills (especially in oceans), building collapses. But besides those two, there also health emergencies for instance Covid-19 which was declared a pandemic by the WHO, or the social and political violence, two examples would include the post-election violence in Kenya in 2007/2008 and the police brutality which occurred in 2022. 
To map all these forms of crisis, use of Visual analytics to display images of crisis and videos with the help of GIS technologies and the programming language, has been rendered helpful as years go by. The main use of visual analytics is supporting the decision on fastest routes to use when it comes to responding to crisis and emergency with the help of visuals interfaces. Together with users’ tweets that are volunteered online to display the geographical content, aids in mapping where these crisis and emergency have occurred and at what rate and how to ensure to include warning systems @qadir_ali_ur. 
Crisis and emergency mapping is the use of GIS imagery that are collected and modelled to fit real time sources from satellites of what is currently happening at certain areas around the world. One of the main organizations that is known for crisis mapping is Ushahidi which monitored the post-election violence and was able to detect how things would look even after the elections in 2017. It is a tool that maps crisis in a number of areas considered to be disastrous, for instance, it was used in Uganda to uncover human rights violations and strengthen voices of the local citizen, it was also used in Pakistan to map, and share info of where floods are likely to occur. 
There is also another tool used when it comes to crisis and emergency mapping, known as the HealthMap, which combines data from different sources to create pictures and map out the current global state of the pandemic (Covid-19). It is a tool that outlays the information about the outbreak and monitors the health with each country and how to avoid such places. This tool is mostly utilized by World Health Organization (WHO) and Center for Disease Control and prevention (CDC) and other Ministry of Health in different countries.

# Conceptual Framework
This section presents the design on understanding how sentimental analysis can be used to aid response when it comes to crisis management. It proposes the system for coordinating the response operations based on affected people from Twitter and how it stimulates the time of response, the level of crisis or emergency, the key social media influencers involved and areas through mapping out where the crisis or emergency has occurred. A proposed STIMULATE system used for rescue management, which used Hadoop and comprised of the Fetcher, Processor, and the rescue scheduler. The fetcher collects tweets from the Twitter API, then an interface allows filtering using certain words and locations, which are pre-processed through replacing of emojis and slang words with English words. The results of the classification are then stored in a database (DB). Then afterwards, the text is classified using certain verbs, and the language use, where they schedule the rescue team based on the level of crisis or emergency involved. Fetcher collects data and frames it in a report form which are keyed in the interface for pre-processing. The fetched data would include images, videos and certain verbs and sentences. The processor, prepares the data, cleans it, analyses it, displays it through visualization and finally maps it and saves it in the cloud for Access. This data could be useful to governments, NGOs, Health organizations and others.

# Gaps from related studies 
One of the Key social media platforms that have been considered to be the most useful is Twitter, which responds directly to current issues affecting humans one way or the other. With different related topics handled by the different scholars, still find other issues that make the study to need further investigation. For instance not understanding the sarcasm, irony or emotions used in the tweets, makes it difficult to dictate whether the rescue teams need to dive deep into responding mode or not. Recently, most of the organizations have being embracing the fact that social media influencers are key people in the society who have a following in their social media accounts, and millions of people would most likely listen to their advice and how to act according to that crisis. This is a study that has not yet been captured well, since the shaping of the public views by the influencers in one area that is currently arising. 
Another gap, is the use GIS technologies, which is currently one of the uprising topics especially in use of drones, and capture areas that might be used to predict the crisis incidents that might occur. However, how rescue teams tailor the strategies based on the geography of the affected areas, is what the study would dive into. Also, Twitter has become one of the used social media platforms that is currently accepted by most organizations, public as well as governments. The integration of twitter to be used as a platform to acquire information into a framework, is one of the key areas that the study would recommend on the methods to ensure capturing all the important aspects of data frameworks that govern their teams. 

# Summary 
This chapter examined the definition of different terms and how they were used, and also displayed a conceptual framework of how Twitter data was collected and pre-processed and finally offered to different consumers who would schedule response time depending on the crisis and emergency level, time used and location of different areas where crisis and emergency occur.
The next chapter will focus on the research methods of how to acquire information from Twitter and the types of ML algorithms to be used.




# References

---

...

